site_name: App-Enhance docs
site_description: 'Documentation for app-enhance projects'
site_author: 'Wojciech Gadzi≈Ñski'
site_url: 'https://app-enhance.github.io'

repo_name: 'ae-docs'
repo_url: 'https://github.com/app-enhance/ae-docs'

theme: 'material'

extra:
  palette:
    primary: 'deep orange'
    accent: 'blue grey'

markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'

remote_branch: master
remote_name: app-enhance.github.io
